Model comparison table function and tests setup.
UBC-MDS/RMLViz pull request #26
Opened 2020-03-07 01:54 UTC by anasm-17

Developed the function and test function

2020-03-07 19:37 UTC, taohuang-ubc requested changes
good work, just minor changes

2020-03-07 19:37 UTC, taohuang-ubc commented on tests/testthat/test-model_comparison_table.R
> +library(purrr)
like fanli say, probably try using `use_package()` to 'load' these packages ? instead of calling it here? remember to run check() afterwards.

2020-03-07 21:20 UTC, flizhou approved these changes
Looks good now!

2020-03-07 21:23 UTC, anasm-17 commented on R/model_comparison_table.R
> +#' @import caret
```suggestion
#' model_comparison_table
#' Takes in training data, testing data,
#' with the target as the last column and
#' fitted models with meaningful names,
#' then generates a model comparison
#' table.
#' @import dplyr
#' @import caret
```

2020-03-07 21:23 UTC, anasm-17 commented on R/model_comparison_table.R
> +#' @import caret
Added description to package

2020-03-07 21:37 UTC, taohuang-ubc approved these changes

2020-03-07 22:45 UTC, merged

2020-03-08 00:48 UTC, anasm-17 commented
resolves issue #23